site_name: Anomalous Wiki
site_url: https://wiki.anomalous.xyz
site_description: Espacio abierto de conocimiento libre.
site_author: Anomalous Research Society
repo_url: https://github.com/anomalouscode/wiki
theme:
  name: material
  language: es
  logo: assets/logo.svg
  favicon: favicon.ico
  palette:
    primary: black
    accent: pink
  features:
    - tabs
    - search.highlight
plugins:
  - search:
      lang: es
      prebuild_index: true
